# No duplicates
typeset -U path
typeset -U cdpath
typeset -U fpath
typeset -U manpath
typeset -xTU PERL5LIB perl5lib
typeset -xTU LD_LIBRARY_PATH ld_library_path

export EDITOR=vi
export LESS="-RSi"
export PAGER="less"
export GRADLE_OPTS='-Dorg.gradle.daemon=true -Dorg.ajoberstar.grgit.auth.sshagent.allow=false -Dorg.ajoberstar.grgit.auth.pageant.allow=false'
export ZPLUG_HOME="$XDG_CONFIG_HOME/zplug"

test -r $XDG_STATE_HOME/brew/github_api_token && export HOMEBREW_GITHUB_API_TOKEN=$(cat $XDG_STATE_HOME/brew/github_api_token)

case "$system" in
    Mac)
	export BROWSER=Safari
	export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
	;;
    *)
	export BROWSER=Chrome
	test -e /usr/local/java && export JAVA_HOME='/usr/local/java'
esac

test -f ~/.LESS_TERMCAP && source ~/.LESS_TERMCAP
