HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
MAILCHECK=0 ## disable mail checking
WORDCHARS=${WORDCHARS//[\/=;]}

CASE_SENSITIVE="false"
COMPLETION_WAITING_DOTS="true"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="false"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# ZSH_CUSTOM=/path/to/new-custom-folder
# HIST_STAMPS="mm/dd/yyyy" # "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"

plugins_prezto+=( git docker )
plugins_local+=( colored-man-pages run-help sdkman git mvn markdown )
plugins_omz+=( safe-paste gnu-utils urltools rsync extract dircycle emoji colorize gitignore gradle grails )
plugins_github+=( Tarrasch/zsh-autoenv Tarrasch/zsh-bd )

fpath=( ~/lib/functions $fpath )

source $zdotdir/.dotfiles/zsh/init.zsh

path=( . ~/bin $path )
cdpath=( .. ~ ~/src )
