ZSH_THEME="qoup"

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
MAILCHECK=0 ## disable mail checking
WORDCHARS=${WORDCHARS//[\/=;]}

CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="false"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# ZSH_CUSTOM=/path/to/new-custom-folder
# HIST_STAMPS="mm/dd/yyyy" # "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"

plugins_prezto=( homebrew )
plugins_omz=( osx safe-paste git-extras gitignore git-prompt gradle grails gnu-utils urltools rsync extract dircycle emoji colorize )
plugins_github=( Tarrasch/zsh-autoenv Tarrasch/zsh-bd )
plugins_local=( git mvn sdkman iterm2 run-help )

umask 022

autoload -U zsh-mime-setup
zsh-mime-setup

zstyle ':vcs_info:*:prompt:bira:*' colors prompt yellow user 244

source $zdotdir/.dotfiles/zsh/dot/zplugrc.prezto

path=( . ~/bin $path )
cdpath=( .. ~ ~/src )
fpath=( ~/lib/functions $fpath )

#fpath=(
#       $zdotdir/{.[z]sh/*.zwc,{.[z]sh,[l]ib/zsh}/{functions{,.local,.$HOST},scripts}}(N)
#       $fpath
#      )
#fpath=( ~/.gvm/springboot/current/shell-completion/zsh $fpath )

for dirname in $fpath; do
  case "$dirname" in
    $zdotdir/.zsh*) fns=( $dirname/*~*~(-N.x:t) ) ;;
#                 *) fns=( $dirname/*~*~(-N.:t)  ) ;;
  esac
  (( $#fns )) && autoload "$fns[@]"
done

